drop table chat;
drop table REPORT;


create table chat(
   id varchar2(100),
   content varchar2(1000),
   nation varchar2(30)
)

CREATE TABLE REPORT 
   ( 
   sex number not null,
   age number not null,
   EXT1 VARCHAR2(50 BYTE) NOT NULL, 
   EXT2 VARCHAR2(50 BYTE) NOT NULL, 
   EXT3 VARCHAR2(50 BYTE) NOT NULL, 
   EXT4 VARCHAR2(50 BYTE) NOT NULL, 
   EXT5 VARCHAR2(50 BYTE) NOT NULL, 
   EXT6 VARCHAR2(50 BYTE) NOT NULL, 
   EXT7 VARCHAR2(50 BYTE) NOT NULL, 
   EXT8 VARCHAR2(50 BYTE) NOT NULL, 
   EXT9 VARCHAR2(50 BYTE) NOT NULL, 
   EXT10 VARCHAR2(50 BYTE) NOT NULL, 
   EST1 VARCHAR2(50 BYTE) NOT NULL, 
   EST2 VARCHAR2(50 BYTE) NOT NULL, 
   EST3 VARCHAR2(50 BYTE) NOT NULL, 
   EST4 VARCHAR2(50 BYTE) NOT NULL, 
   EST5 VARCHAR2(50 BYTE) NOT NULL, 
   EST6 VARCHAR2(50 BYTE) NOT NULL, 
   EST7 VARCHAR2(50 BYTE) NOT NULL, 
   EST8 VARCHAR2(50 BYTE) NOT NULL, 
   EST9 VARCHAR2(50 BYTE) NOT NULL, 
   EST10 VARCHAR2(50 BYTE) NOT NULL, 
   AGR1 VARCHAR2(50 BYTE) NOT NULL, 
   AGR2 VARCHAR2(50 BYTE) NOT NULL, 
   AGR3 VARCHAR2(50 BYTE) NOT NULL, 
   AGR4 VARCHAR2(50 BYTE) NOT NULL, 
   AGR5 VARCHAR2(50 BYTE) NOT NULL, 
   AGR6 VARCHAR2(50 BYTE) NOT NULL, 
   AGR7 VARCHAR2(50 BYTE) NOT NULL, 
   AGR8 VARCHAR2(50 BYTE) NOT NULL, 
   AGR9 VARCHAR2(50 BYTE) NOT NULL, 
   AGR10 VARCHAR2(50 BYTE) NOT NULL, 
   CSN1 VARCHAR2(50 BYTE) NOT NULL, 
   CSN2 VARCHAR2(50 BYTE) NOT NULL, 
   CSN3 VARCHAR2(50 BYTE) NOT NULL, 
   CSN4 VARCHAR2(50 BYTE) NOT NULL, 
   CSN5 VARCHAR2(50 BYTE) NOT NULL, 
   CSN6 VARCHAR2(50 BYTE) NOT NULL, 
   CSN7 VARCHAR2(50 BYTE) NOT NULL, 
   CSN8 VARCHAR2(50 BYTE) NOT NULL, 
   CSN9 VARCHAR2(50 BYTE) NOT NULL, 
   CSN10 VARCHAR2(50 BYTE) NOT NULL, 
   OPN1 VARCHAR2(50 BYTE) NOT NULL, 
   OPN2 VARCHAR2(50 BYTE) NOT NULL, 
   OPN3 VARCHAR2(50 BYTE) NOT NULL, 
   OPN4 VARCHAR2(50 BYTE) NOT NULL, 
   OPN5 VARCHAR2(50 BYTE) NOT NULL, 
   OPN6 VARCHAR2(50 BYTE) NOT NULL, 
   OPN7 VARCHAR2(50 BYTE) NOT NULL, 
   OPN8 VARCHAR2(50 BYTE) NOT NULL, 
   OPN9 VARCHAR2(50 BYTE) NOT NULL, 
   OPN10 VARCHAR2(50 BYTE) NOT NULL
   ); 
   
   
   select * from report;
   select * from chat;
   
   insert into chat values('sj','☆저랑 함께 떠나실 분 구함☆','말레이시아');
   insert into chat values('mmin','영국이라니~ 역시 제 2의 고향이네요','영국');
   insert into chat values('jun','와~딱이네요','러시아');
   insert into chat values('bae','당장 호주로 떠나야겠어요','호주');
   insert into chat values('kim','앗살람말레이쿵','파키스탄');
   


   
   